version: '2.2'
services:
 elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
  container_name: elasticsearch
  environment:
   - cluster.name=avi-cluster
   - bootstrap.memory_lock=true
   - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  ulimits:
   memlock:
    soft: -1
    hard: -1
  volumes:
   - esdata1:/usr/share/elasticsearch/data
  ports:
   - 9200:9200
  networks:
   - esnet
 kibana:
  image: docker.elastic.co/kibana/kibana:6.2.3
  volumes:
   - kibdata1:/usr/share/kibana/data
  ports:
   - 5601:5601
  networks:
   - esnet
  environment:
   ELASTICSEARCH_URL: http://elasticsearch:9200
   server.host: 0.0.0.0
   logging.dest: /opt/apl/avi/log
volumes:
 esdata1:
  driver: local 
 kibdata1:
  driver: local
networks:
 esnet:
